# usar la imagen oficial de Bun
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# instalar dependencias en directorio temporal esto las cacheará y acelerará futuras compilaciones
FROM base AS install
RUN mkdir -p /temp/dev
ENV HUSKY=0
ENV DO_NOT_TRACK=1
ENV NEXT_TELEMETRY_DISABLED=1
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# instalar con --production (excluir devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

# copiar node_modules desde el directorio temporal luego copiar todos los archivos del proyecto (no ignorados) en la imagen
FROM base AS prerelease
ENV HUSKY=0
ENV DO_NOT_TRACK=1
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=install /temp/dev/node_modules node_modules
COPY . .
# RUN bun run build && \
#     cp -r public .next/standalone/ && \
#     cp -r .next/static .next/standalone/.next/

# [opcional] tests y build
# RUN bun test
RUN bun run build

USER bun
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "run", "server.js" ]